### ISSUE TITLE
Qt5 dependency error

### ISSUE THREAD

**Issue by pavmk** [uavos/apx-gcs-plugin#1]
I need Qt5 positioning module, so, I replace string
`COMPONENTS Core QuickCompiler`
on
`COMPONENTS Core QuickCompiler Positioning`
But I'm still have error:
`fatal error: QGeoCoordinate: No such file or directory`

How to fix it?

**Comment by uavinda** [comment]
Is this still actual?

**Comment by pavmk** [comment]
I don't now.
